
services:
  database:
    image: postgres:16-alpine
    container_name: crm-database
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    volumes:
      - ./database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - crmnet

  crm:
    build:
      context: ./crm
      dockerfile: Dockerfile
    container_name: crm
    env_file:
      - ./crm/.env
    ports:
      - "${CRM_PORT}:80"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:80 || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 10
    networks:
      - crmnet

volumes:
  database:

networks:
  crmnet:
    driver: bridge
